### PR TITLE
database: add a schema version number

### LINKED ISSUE #405: Display clearer error message when encountering errors due to database schema changes
A common error for people juggling multiple versions of Wake at the same time is using a different version of Wake than was used to initialize the SQLite3 database. For example, you encounter this error when trying to run Wake 0.17.2 on a database initialized with Wake 0.18.0:

```
Could not insert a job; sqlite3_step: NOT NULL constraint failed: jobs.signature
The failing statement was: insert into jobs(run_id, use_id, directory, commandline, environment, stack, stdin) values(?, ?1, ?, ?, ?, ?, ?)
```

### PR DESCRIPTION
**Pull request by terpstra**
This way we can detect incompatible databases gracefully.
Fixes #405.

### CODE REVIEW

File: src/database.cpp [hunk 1]
```diff
@@ -156,7 +183,17 @@ std::string Database::open(bool wait, bool memory) {
   while (true) {
     char *fail;
     ret = sqlite3_exec(imp->db, schema_sql, 0, 0, &fail);
-    if (ret == SQLITE_OK) break;
+    if (ret == SQLITE_OK) {
+      const char *get_version = "select (select count(row_id) from entropy), (select max(version) from schema);";
```
Comment (richardxia) [inline src/database.cpp:187]: What is this `entropy` thing about?

File: src/database.cpp [hunk 2]
```diff
@@ -156,7 +183,17 @@ std::string Database::open(bool wait, bool memory) {
...
+      const char *set_version = "insert or ignore into schema(version) values(" SCHEMA_VERSION ");";
+      ret = sqlite3_exec(imp->db, get_version, &schema_cb, 0, 0);
+      if (ret == SQLITE_OK) {
+        sqlite3_exec(imp->db, set_version, 0, 0, 0);
+        break;
+      } else {
+        return "produced by an incompatible verison of wake; remove it.";
```
[the remark this answers is not in the document]
Comment (terpstra) [reply src/database.cpp:194]: You do not need to run `wake --init` in v0.18. If it finds a wit-lock.json, it will autoinit a wake.db.

[the remark this answers is not in the document]
Comment (terpstra) [reply src/database.cpp:194]: The error FYI is: 
```
Failed to open wake.db: produced by an incompatible verison of wake; remove it.
```

File: src/database.cpp (hunk 1 above)
Comment (terpstra) [reply src/database.cpp:187]: Wake uses hashes to create signatures for some functions in build rules. If those build rules change, they get re-executed. The hash function I use needs a seed to prevent intentional collision attacks. The first time the database is created, a persistent random seed is chosen which will be used for all hashes. That way the hashes in the database do not change values between runs.

In this context, I am using the entropy as a means to detect that the database is "fresh"/unused. That's needed because earlier versions do not have a schema(version) to check.

File: src/database.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (richardxia) [reply src/database.cpp:194]: > You do not need to run wake --init in v0.18. If it finds a wit-lock.json, it will autoinit a wake.db.

Neat, I remember this now that you mention it, but totally forgot.

And thanks, yes, I agree that error message is pretty clear.

File: src/database.cpp (hunk 1 above)
Comment (richardxia) [reply src/database.cpp:187]: OK, thanks for the additional context. I think it's worth adding a comment to describe that the choice of table here is not really important, and that it's just to detect a fresh DB. As an outside reader of the code, I was reading more into the entropy than was actually relevant for this specific use case.

Comment (terpstra) [reply src/database.cpp:188]: Comment added.

Comment (richardxia) [reply src/database.cpp:188]: Thanks!
