### PR TITLE
LSP: fix documentation hover for `tuple` and `data`

### LINKED ISSUE #820: LSP: documentation hover broken for `tuple` and `data`
The current approach to linking documentation comments to definitions works great for normal top-level `def`s.

However, when a comment precedes a `data` or `tuple` definition, several symbols are introduced. The LSP currently only associates the comments to the first such symbol.

For example,
```
# This comment only shows up for `Nil`, not for `,` (also not `List`)
export data List a =
    Nil
    (head: a), (tail: List a)
```

Another example.
```
# This comment only shows up for Pet, not `getPetName` or `getPetAge`
tuple Pet =
  Name: String
  Age: Integer
```

### PR DESCRIPTION
**Pull request by elena-pudovkina**
Outer comments are now also bound to symbols introduced in a `tuple` or `data` definition. They appear after the inner comment:
image

Definitions which have the same location are now merged into a single definition with the documentation containing:
- Name and type of the symbol
- Inner documentation of the symbol
- List of definitions introduced at this location
- Outer documentation

image

image

Fixes #820.

### CODE REVIEW

File: src/util/location.h [hunk 1]
```diff
@@ -55,9 +55,18 @@ struct Location {
...
 
   bool operator < (const Location &l) const {
-    if (filename == l.filename) { return start < l.start; }
+    if (filename == l.filename) {
+      if (start == l.start) {
+        return end < l.end;
+      }
+      return start < l.start;
+    }
     return filename < l.filename;
```
Comment (terpstra) [inline src/util/location.h:64]: So, to prevent nesting when comparing multiple tuple elements, people usually write this as:
```
if (a != b) return a < b;
if (c != d) return c < d;
if (e != f) return e < f;
return g < h;
```

File: tools/lsp-wake/symbol_definition.h [hunk 2]
```diff
@@ -43,12 +44,20 @@ struct SymbolDefinition {
...
     std::string documentation;
+    std::string outerDocumentation;
+    std::vector<std::pair<std::string, std::string>> introduces;
 
     SymbolDefinition(std::string _name, Location _location, std::string _type, SymbolKind _symbolKind, bool _isGlobal) :
     name(std::move(_name)), location(std::move(_location)), type(std::move(_type)), symbolKind(_symbolKind),
     isGlobal(_isGlobal) {}
 
     bool operator < (const SymbolDefinition &def) const {
+      if (!(this->location < def.location) && !(def.location < this->location)) {
```
Comment (terpstra) [inline tools/lsp-wake/symbol_definition.h:55]: Isn't this just `==`?

File: tools/lsp-wake/symbol_definition.h [hunk 3]
```diff
@@ -43,12 +44,20 @@ struct SymbolDefinition {
...
+        if (this->name == def.name) {
+          return this->type < def.type;
+        }
+        return this->name < def.name;
+      }
```
Comment (terpstra) [inline tools/lsp-wake/symbol_definition.h:60]: Also, I'd recommend the same pattern for comparing tuples from earlier.

File: tools/lsp-wake/astree.cpp [hunk 4]
```diff
@@ -437,10 +482,28 @@ std::string ASTree::sanitizeComment(std::string comment) {
...
+  comment.back().first += text;
+}
+
 ASTree::SymbolUsage::SymbolUsage(Location _usage, Location _definition) : usage(std::move(_usage)), definition(std::move(_definition)) {}
 
-ASTree::Comment::Comment(std::string _comment_text, Location _location)
-: comment_text(std::move(_comment_text)), location(std::move(_location)) {}
+ASTree::Comment::Comment(std::string _comment_text, Location _location, int _level)
+: comment_text(std::move(_comment_text)), location(std::move(_location)) {
+  level = _level;
```
Comment (terpstra) [inline tools/lsp-wake/astree.cpp:505]: You can (and probably should) just add a `level(_level)`

File: tools/lsp-wake/astree.cpp [hunk 5]
```diff
@@ -437,10 +482,28 @@ std::string ASTree::sanitizeComment(std::string comment) {
   return comment;
 }
 
+std::string ASTree::composeOuterComment(std::vector<std::pair<std::string, int>> comment) {
+  std::string composed;
+  for (int i = (int) comment.size() - 2; i >= 0; i--) {
```
Comment (terpstra) [inline tools/lsp-wake/astree.cpp:487]: So, the reason you get a warning here is that `size()` might not fit in an `int`. You're probably correct, and it will fit, so the override is ok. I generally do this sometimes, too. However, it is usually better to use a `size_t` to be safe (also the compiler likes these better when optimizing). Unfortunately, `size_t` cannot accommodate negative numbers.

I would probably leave the code how you wrote it, but wanted to point out the pitfalls of the cast.

**Review by terpstra — APPROVED** [review]
Looks good!

**Comment by terpstra** [comment]
I saw you closed a bunch of issues and PRs by hand. It's better to write:

Closes #833.
Fixes #820.
Fixes #821.

These now get linked to this PR and closed when this PR merges.

File: src/util/location.h (hunk 1 above)
Comment (elena-pudovkina) [reply src/util/location.h]: Done

File: tools/lsp-wake/astree.cpp (hunk 4 above)
Comment (elena-pudovkina) [reply tools/lsp-wake/astree.cpp]: Done

File: tools/lsp-wake/symbol_definition.h (hunk 2 above)
Comment (elena-pudovkina) [reply tools/lsp-wake/symbol_definition.h]: It is, fixed

File: tools/lsp-wake/symbol_definition.h (hunk 3 above)
Comment (elena-pudovkina) [reply tools/lsp-wake/symbol_definition.h]: Done

File: tools/lsp-wake/astree.cpp (hunk 5 above)
Comment (elena-pudovkina) [reply tools/lsp-wake/astree.cpp:487]: Yes, I understand. Left as is

**Comment by elena-pudovkina** [comment]
> I saw you closed a bunch of issues and PRs by hand. It's better to write:
> 
> Closes #833. Fixes #820. Fixes #821.
> 
> These now get linked to this PR and closed when this PR merges.

I closed PR #833 because it doesn't fix issue #821. It is still not fixed. Should I write about it somewhere?

**Comment by terpstra** [comment]
> > I saw you closed a bunch of issues and PRs by hand. It's better to write:
> > Closes #833. Fixes #820. Fixes #821.
> > These now get linked to this PR and closed when this PR merges.
> 
> I closed PR #833 because it doesn't fix issue #821. It is still not fixed. Should I write about it somewhere?

Not necessary.
